// <auto-generated />
using System;
using CityRoots.EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityRoots.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityRoots.Core.Models.AiPredict", b =>
                {
                    b.Property<int>("AiPredictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiPredictId"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsIll")
                        .HasColumnType("bit");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiPredictId");

                    b.ToTable("AiPredicts");

                    b.HasData(
                        new
                        {
                            AiPredictId = -1,
                            ArabicName = "جرب التفاح",
                            Diagnosis = "بقع بنية على الثمار، بقع صفراء على الأوراق",
                            EnglishName = "Apple Scab",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تقليم الأغصان المصابة"
                        },
                        new
                        {
                            AiPredictId = -2,
                            ArabicName = "العفن الأسود في التفاح",
                            Diagnosis = "بقع سوداء على الثمار، تساقط الأوراق",
                            EnglishName = "Apple Black Rot",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، إزالة الأجزاء المصابة"
                        },
                        new
                        {
                            AiPredictId = -3,
                            ArabicName = "صدأ التفاح الناتج عن الأرز",
                            Diagnosis = "بقع برتقالية على الأوراق، تشوهات في الثمار",
                            EnglishName = "Apple Cedar Rust",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، زراعة أصناف مقاومة"
                        },
                        new
                        {
                            AiPredictId = -4,
                            ArabicName = "البياض الدقيقي على الكرز",
                            Diagnosis = "ظهور طبقة بيضاء دقيقية على الأوراق والبراعم والثمار.\nتوقف نمو الأوراق وتشوهها.\nتساقط الأوراق والثمار.",
                            EnglishName = "Cherry powdery mildew",
                            IsIll = true,
                            Recommendation = "استخدام مبيدات فطرية مناسبة.\nتقليم الأغصان المصابة.\nزراعة أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -5,
                            ArabicName = "بقعة الورقة الرمادية على الذرة",
                            Diagnosis = "ظهور بقع رمادية على أوراق الذرة.\nتطور البقع إلى خطوط رمادية داكنة.\nموت الأنسجة المصابة.",
                            EnglishName = "Corn Gray Leaf Spot",
                            IsIll = true,
                            Recommendation = "زراعة أصناف مقاومة.\nتدوير المحاصيل.\nاستخدام مبيدات فطرية."
                        },
                        new
                        {
                            AiPredictId = -6,
                            ArabicName = "صدأ الذرة الشائع",
                            Diagnosis = "ظهور بقع برتقالية أو بنية على سطح الأوراق.\nتطور البقع إلى بثرات تنتشر منها الأبواغ الفطرية.\nتقليل محصول الذرة.",
                            EnglishName = "Corn Common Rust",
                            IsIll = true,
                            Recommendation = "زراعة أصناف مقاومة.\nاستخدام مبيدات فطرية.\nتدوير المحاصيل."
                        },
                        new
                        {
                            AiPredictId = -7,
                            ArabicName = "بقعة الورقة الشمالية على الذرة",
                            Diagnosis = "ظهور بقع بيضاوية الشكل على أوراق الذرة.\nتطور البقع إلى خطوط طويلة داكنة اللون.\nموت الأنسجة المصابة",
                            EnglishName = "Corn Northern Leaf Blight",
                            IsIll = true,
                            Recommendation = "زراعة أصناف مقاومة.\nتدوير المحاصيل.\nاستخدام مبيدات فطرية."
                        },
                        new
                        {
                            AiPredictId = -8,
                            ArabicName = "العفن الأسود على العنب",
                            Diagnosis = "ظهور بقع بنية داكنة على الأوراق والعنقود.\nتطور البقع إلى اللون الأسود.\nموت الأنسجة المصابة.",
                            EnglishName = "Grape Black Rot",
                            IsIll = true,
                            Recommendation = "تقليم الأغصان المصابة.\nاستخدام مبيدات فطرية.\nزراعة أصناف مقاومة"
                        },
                        new
                        {
                            AiPredictId = -9,
                            ArabicName = "الجدري الأسود على العنب",
                            Diagnosis = "ظهور بقع سوداء صغيرة على الأوراق.\nتطور البقع إلى قرحات غائرة.\nضعف نمو الكرمة.",
                            EnglishName = "Grape Black Measles",
                            IsIll = true,
                            Recommendation = "تقليم الأغصان المصابة.\nاستخدام مبيدات فطرية.\nزراعة أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -10,
                            ArabicName = "مرض اصفرار الشجر الحمضي",
                            Diagnosis = "اصفرار الأوراق.\nتقزم الشجرة.\nثمار صغيرة وقليلة العصير.",
                            EnglishName = "Orange Huanglongbing",
                            IsIll = true,
                            Recommendation = "إزالة الأشجار المصابة.\nمكافحة الحشرات الناقلة للمرض.\nزراعة أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -11,
                            ArabicName = "البقعة البكتيرية على الدراق",
                            Diagnosis = "ظهور بقع صغيرة دائرية على الأوراق والثمار.\nتطور البقع إلى قرحات.\nتساقط الأوراق والثمار.",
                            EnglishName = "Peach bacterial spot",
                            IsIll = true,
                            Recommendation = "تقليم الأغصان المصابة.\nاستخدام مبيدات بكتيرية.\nزراعة أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -12,
                            ArabicName = "بقعة الورقة على العنب",
                            Diagnosis = "ظهور بقع بنية على الأوراق.\nتطور البقع إلى مناطق ميتة.\nتساقط الأوراق.",
                            EnglishName = "Grape Leaf Blight",
                            IsIll = true,
                            Recommendation = "تقليم الأغصان المصابة.\nاستخدام مبيدات فطرية.\nزراعة أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -13,
                            ArabicName = "بقعة بكتيرية على الفلفل",
                            Diagnosis = "بقع صغيرة داكنة مائية على الأوراق والثمار.",
                            EnglishName = "Pepper Bacterial Spot",
                            IsIll = true,
                            Recommendation = "مبيدات نحاسية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -14,
                            ArabicName = "البياض المبكر على البطاطس",
                            Diagnosis = "بقع كبيرة بنية داكنة على الأوراق مع حلقات متحدة المركز.",
                            EnglishName = "Potato Early Blight",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -15,
                            ArabicName = "البياض المتأخر على البطاطس",
                            Diagnosis = "آفات مائية على الأوراق والساق، نمو فطري أبيض على الجانب السفلي من الأوراق.",
                            EnglishName = "Potato Late Blight",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -16,
                            ArabicName = "البياض الدقيقي على القرع",
                            Diagnosis = "نمو أبيض بودري على الأوراق والثمار.",
                            EnglishName = "Squash Powdery Mildew",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، أصناف مقاومة، تهوية جيدة."
                        },
                        new
                        {
                            AiPredictId = -17,
                            ArabicName = "حروق أوراق الفراولة",
                            Diagnosis = "حواف أوراق بنية ميتة.",
                            EnglishName = "Strawberry Leaf Scorch",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، ري مناسب، تهوية جيدة."
                        },
                        new
                        {
                            AiPredictId = -18,
                            ArabicName = "بقعة بكتيرية على الطماطم",
                            Diagnosis = "بقع صغيرة داكنة مائية على الأوراق والثمار.",
                            EnglishName = "Tomato Bacterial Spot",
                            IsIll = true,
                            Recommendation = "مبيدات نحاسية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -19,
                            ArabicName = "البياض المبكر على الطماطم",
                            Diagnosis = "بقع كبيرة بنية داكنة على الأوراق مع حلقات متحدة المركز.",
                            EnglishName = "Tomato Early Blight",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -20,
                            ArabicName = "البياض المتأخر على الطماطم",
                            Diagnosis = "آفات مائية على الأوراق والساق، نمو فطري أبيض على الجانب السفلي من الأوراق.",
                            EnglishName = "Tomato Late Blight",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -21,
                            ArabicName = "العفن الورقي على الطماطم",
                            Diagnosis = "بقع صفراء بنية على السطح العلوي للأوراق، عفن رمادي على السطح السفلي للأوراق.",
                            EnglishName = "Tomato Leaf Mold",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تهوية جيدة، تجنب الري العلوي."
                        },
                        new
                        {
                            AiPredictId = -22,
                            ArabicName = "بقعة سيبتوريا على الطماطم",
                            Diagnosis = "بقع صغيرة بنية داكنة مع مراكز بيضاء على الأوراق.",
                            EnglishName = "Tomato Septoria Leaf Spot",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -23,
                            ArabicName = "سوس العنكبوت ذو البقعتين",
                            Diagnosis = "حشرات صغيرة صفراء خضراء تمتص العصارة من الأوراق، مما يسبب بقعًا صفراء وتلونًا.",
                            EnglishName = "Tomato Spider Mites",
                            IsIll = true,
                            Recommendation = "صابون حشري، حشرات مفترسة، تجنب استخدام المبيدات."
                        },
                        new
                        {
                            AiPredictId = -24,
                            ArabicName = "بقعة الهدف على الطماطم",
                            Diagnosis = "بقع كبيرة ذات حلقات متحدة المركز على الأوراق.",
                            EnglishName = "Tomato Target Spot",
                            IsIll = true,
                            Recommendation = "مبيدات فطرية، تناوب المحاصيل، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -25,
                            ArabicName = "فيروس موزاييك الطماطم",
                            Diagnosis = "أوراق مرقطة وصفراء ومشوهة، نمو متقزم.",
                            EnglishName = "Tomato Mosaic Virus",
                            IsIll = true,
                            Recommendation = "بذور خالية من الأمراض، نظافة، مكافحة الحشرات."
                        },
                        new
                        {
                            AiPredictId = -26,
                            ArabicName = "فيروس تجعد الأوراق الصفراء للطماطم",
                            Diagnosis = "اصفرار وتجعد وانحناء أوراق لأسفل.",
                            EnglishName = "Tomato Yellow Leaf Curl Virus",
                            IsIll = true,
                            Recommendation = "مكافحة الحشرات (ذبابة بيضاء)، أصناف مقاومة."
                        },
                        new
                        {
                            AiPredictId = -27,
                            ArabicName = "طماطم صحية",
                            EnglishName = "Tomato healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -28,
                            ArabicName = "فراولة صحية",
                            EnglishName = "Strawberry healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -29,
                            ArabicName = "فول صويا صحي",
                            EnglishName = "Soybean healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -30,
                            ArabicName = "توت أحمر صحي",
                            EnglishName = "Raspberry healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -31,
                            ArabicName = "بطاطس صحية",
                            EnglishName = "Potato healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -32,
                            ArabicName = "فلفل صحي",
                            EnglishName = "Pepper healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -33,
                            ArabicName = "خوخ صحي",
                            EnglishName = "Peach healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -34,
                            ArabicName = "عنب صحي",
                            EnglishName = "Grape healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -35,
                            ArabicName = "ذرة صحية",
                            EnglishName = "Corn healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -36,
                            ArabicName = "كرز صحي",
                            EnglishName = "Cherry healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -37,
                            ArabicName = "توت أرزق صحي",
                            EnglishName = "Blueberry healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -38,
                            ArabicName = "تفاح صحي",
                            EnglishName = "Apple healthy",
                            IsIll = false
                        },
                        new
                        {
                            AiPredictId = -39,
                            ArabicName = "صورة بدون أوراق",
                            EnglishName = "Background without leaves",
                            IsIll = false
                        });
                });

            modelBuilder.Entity("CityRoots.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CityRoots.Core.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedPriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropId");

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            CropId = 1,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 16.00m,
                            ImageUrl = "https://example.com/images/wheat.jpg",
                            Name = "قمح",
                            RiskDescription = "منخفض المخاطر بسبب الطلب المستقر",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 2,
                            CropTypeId = 1,
                            CurrentPrice = 14.00m,
                            ExpectedPriceChange = 11.00m,
                            ImageUrl = "https://example.com/images/corn.jpg",
                            Name = "ذرة",
                            RiskDescription = "متوسط المخاطر بسبب الظروف الجوية",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 3,
                            CropTypeId = 2,
                            CurrentPrice = 18.00m,
                            ExpectedPriceChange = 10.00m,
                            ImageUrl = "https://example.com/images/apple.jpg",
                            Name = "تفاح",
                            RiskDescription = "مرتفع المخاطر بسبب تقلبات السوق",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 4,
                            CropTypeId = 2,
                            CurrentPrice = 16.00m,
                            ExpectedPriceChange = 16.00m,
                            ImageUrl = "https://example.com/images/orange.jpg",
                            Name = "برتقال",
                            RiskDescription = "منخفض المخاطر مع طلب مستقر",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 5,
                            CropTypeId = 3,
                            CurrentPrice = 19.00m,
                            ExpectedPriceChange = 18.00m,
                            ImageUrl = "https://example.com/images/tomato.jpg",
                            Name = "طماطم",
                            RiskDescription = "متوسط المخاطر بسبب قيود التصدير",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 6,
                            CropTypeId = 3,
                            CurrentPrice = 11.00m,
                            ExpectedPriceChange = 11.00m,
                            ImageUrl = "https://example.com/images/cucumber.jpg",
                            Name = "خيار",
                            RiskDescription = "منخفض المخاطر مع إنتاج وفير",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 7,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 14.00m,
                            ImageUrl = "https://example.com/images/rice.jpg",
                            Name = "أرز",
                            RiskDescription = "منخفض المخاطر مع طلب عالمي مرتفع",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 8,
                            CropTypeId = 1,
                            CurrentPrice = 25.00m,
                            ExpectedPriceChange = 25.00m,
                            ImageUrl = "https://example.com/images/oats.jpg",
                            Name = "شوفان",
                            RiskDescription = "منخفض المخاطر ومناسب للعديد من التطبيقات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 9,
                            CropTypeId = 2,
                            CurrentPrice = 22.00m,
                            ExpectedPriceChange = 23.00m,
                            ImageUrl = "https://example.com/images/grape.jpg",
                            Name = "عنب",
                            RiskDescription = "متوسط المخاطر بسبب الأمراض والآفات",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 10,
                            CropTypeId = 2,
                            CurrentPrice = 17.00m,
                            ExpectedPriceChange = 17.00m,
                            ImageUrl = "https://example.com/images/banana.jpg",
                            Name = "موز",
                            RiskDescription = "منخفض المخاطر مع طلب استهلاكي كبير",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 11,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/potato.jpg",
                            Name = "بطاطس",
                            RiskDescription = "منخفض المخاطر مع استخدامات متعددة",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 12,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/carrot.jpg",
                            Name = "جزر",
                            RiskDescription = "منخفض المخاطر ومصدر غني بالفيتامينات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 13,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/soybean.jpg",
                            Name = "فول الصويا",
                            RiskDescription = "متوسط المخاطر بسبب تقلبات الأسواق العالمية",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 14,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/barley.jpg",
                            Name = "شعير",
                            RiskDescription = "منخفض المخاطر مع استخدامات متنوعة في الصناعة",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 15,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/strawberry.jpg",
                            Name = "فراولة",
                            RiskDescription = "مرتفع المخاطر بسبب موسمية الإنتاج",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 16,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/pear.jpg",
                            Name = "كمثرى",
                            RiskDescription = "متوسط المخاطر بسبب مشاكل التخزين",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 17,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/onion.jpg",
                            Name = "بصل",
                            RiskDescription = "منخفض المخاطر مع طلب أساسي في الطهي",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 18,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/cabbage.jpg",
                            Name = "ملفوف",
                            RiskDescription = "منخفض المخاطر ومصدر جيد للفيتامينات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 19,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/sorghum.jpg",
                            Name = "الذرة الرفيعة",
                            RiskDescription = "منخفض المخاطر، مقاومة للجفاف",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 20,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/rye.jpg",
                            Name = "الجاودار",
                            RiskDescription = "منخفض المخاطر، يستخدم في الخبز وصناعة الأعلاف",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 21,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/mango.jpg",
                            Name = "مانجو",
                            RiskDescription = "متوسط المخاطر، حساسية للطقس البارد",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 22,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/pineapple.jpg",
                            Name = "أناناس",
                            RiskDescription = "متوسط المخاطر، فترة نمو طويلة",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 23,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/pepper.jpg",
                            Name = "فلفل",
                            RiskDescription = "متوسط المخاطر، عرضة للأمراض",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 24,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/eggplant.jpg",
                            Name = "باذنجان",
                            RiskDescription = "منخفض المخاطر، ينمو في الطقس الدافئ",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 25,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/lentils.jpg",
                            Name = "العدس",
                            RiskDescription = "منخفض المخاطر، محصول غذائي أساسي",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 26,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/beans.jpg",
                            Name = "الفاصوليا",
                            RiskDescription = "منخفض المخاطر، محصول غذائي أساسي",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 27,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/kiwi.jpg",
                            Name = "كيوي",
                            RiskDescription = "مرتفع المخاطر، يتطلب مناخًا خاصًا",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 28,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/peach.jpg",
                            Name = "خوخ",
                            RiskDescription = "متوسط المخاطر، عرضة للأمراض والآفات",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 29,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/spinach.jpg",
                            Name = "سبانخ",
                            RiskDescription = "منخفض المخاطر، دورة نمو قصيرة",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 30,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/cauliflower.jpg",
                            Name = "قرنبيط",
                            RiskDescription = "متوسط المخاطر، يتطلب رعاية خاصة",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 31,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/beetroot.jpg",
                            Name = "بنجر",
                            RiskDescription = "منخفض المخاطر، محصول جذري متعدد الاستخدامات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 32,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/almond.jpg",
                            Name = "لوز",
                            RiskDescription = "مرتفع المخاطر، يتأثر بالظروف الجوية والصقيع",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 33,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/walnut.jpg",
                            Name = "جوز",
                            RiskDescription = "مرتفع المخاطر، عرضة للأمراض والآفات",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 34,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/kale.jpg",
                            Name = "كرنب",
                            RiskDescription = "منخفض المخاطر، محصول شتوي مقاوم للبرد",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 35,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/peanut.jpg",
                            Name = "فول سوداني",
                            RiskDescription = "متوسط المخاطر، يتطلب ظروف تربة ومناخ محددة",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 36,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/hazelnut.jpg",
                            Name = "بندق",
                            RiskDescription = "مرتفع المخاطر، يتطلب تقليمًا خاصًا",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 37,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/pumpkin.jpg",
                            Name = "يقطين",
                            RiskDescription = "منخفض المخاطر، ينمو بسهولة في التربة الغنية",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 38,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/flax.jpg",
                            Name = "الكتان",
                            RiskDescription = "منخفض المخاطر، محصول متعدد الاستخدامات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 39,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/fig.jpg",
                            Name = "تين",
                            RiskDescription = "مرتفع المخاطر، يتطلب مناخًا دافئًا ومستقرًا",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 40,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/pomegranate.jpg",
                            Name = "رمان",
                            RiskDescription = "متوسط المخاطر، حساس للتغيرات في الرطوبة",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 41,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/radish.jpg",
                            Name = "فجل",
                            RiskDescription = "منخفض المخاطر، محصول سريع النمو",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 42,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/cherry.jpg",
                            Name = "كرز",
                            RiskDescription = "مرتفع المخاطر، حساس للظروف الجوية والصقيع",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 43,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/turnip.jpg",
                            Name = "لفت",
                            RiskDescription = "منخفض المخاطر، محصول جذري متين",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 44,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/chickpeas.jpg",
                            Name = "حمص",
                            RiskDescription = "منخفض المخاطر، محصول غذائي غني بالبروتين",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 45,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/okra.jpg",
                            Name = "بامية",
                            RiskDescription = "متوسط المخاطر، حساس للبرد",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 46,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/olives.jpg",
                            Name = "زيتون",
                            RiskDescription = "مرتفع المخاطر، يتطلب سنوات عديدة لإنتاج محصول",
                            RiskLevel = "مرتفع"
                        },
                        new
                        {
                            CropId = 47,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/anise.jpg",
                            Name = "يانسون",
                            RiskDescription = "منخفض المخاطر، يستخدم في العديد من الصناعات",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 48,
                            CropTypeId = 3,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/ginger.jpg",
                            Name = "زنجبيل",
                            RiskDescription = "متوسط المخاطر، يتطلب تربة دافئة ورطبة",
                            RiskLevel = "متوسط"
                        },
                        new
                        {
                            CropId = 49,
                            CropTypeId = 1,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/millet.jpg",
                            Name = "دخن",
                            RiskDescription = "منخفض المخاطر، محصول مقاوم للجفاف",
                            RiskLevel = "منخفض"
                        },
                        new
                        {
                            CropId = 50,
                            CropTypeId = 2,
                            CurrentPrice = 15.00m,
                            ExpectedPriceChange = 3.00m,
                            ImageUrl = "https://example.com/images/gooseberry.jpg",
                            Name = "عنب الثعلب",
                            RiskDescription = "مرتفع المخاطر، عرضة للأمراض والآفات",
                            RiskLevel = "مرتفع"
                        });
                });

            modelBuilder.Entity("CityRoots.Core.Models.CropType", b =>
                {
                    b.Property<int>("CropTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropTypeId");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Cycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExpectedYield")
                        .HasColumnType("float");

                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CycleId");

                    b.HasIndex("CropId");

                    b.HasIndex("ParcelId");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("CityRoots.Core.Models.CycleNotificationLog", b =>
                {
                    b.Property<int>("NotificationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationLogId"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("CycleNotificationType")
                        .HasColumnType("int");

                    b.Property<int?>("InvestmentRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationLogId");

                    b.HasIndex("CycleId");

                    b.ToTable("cycleNotificationLogs");
                });

            modelBuilder.Entity("CityRoots.Core.Models.CycleUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrowthRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityCheck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UpdateId");

                    b.HasIndex("CycleId");

                    b.ToTable("CycleUpdates");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmerId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("CityRoots.Core.Models.FavoriteFarmers", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("userId", "FarmerId");

                    b.HasIndex("FarmerId");

                    b.ToTable("favoriteFarmers");
                });

            modelBuilder.Entity("CityRoots.Core.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("feedBacks");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Harvest", b =>
                {
                    b.Property<int>("HarvestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarvestId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int?>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlLowedToShowUpdatesToMerchant")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Yield")
                        .HasColumnType("float");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HarvestId");

                    b.HasIndex("CropId");

                    b.HasIndex("CycleId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.HarvestNotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ForWho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HarvestId")
                        .HasColumnType("int");

                    b.Property<int>("HarvestNotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PurchaseRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.ToTable("HarvestNotificationLogs");
                });

            modelBuilder.Entity("CityRoots.Core.Models.InvestmentRequest", b =>
                {
                    b.Property<int>("InvestmentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestmentRequestId"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequestedProfitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestmentRequestId");

                    b.HasIndex("CycleId");

                    b.HasIndex("InvestorId");

                    b.ToTable("InvestmentRequests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Investor", b =>
                {
                    b.Property<int>("InvestorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestorId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("CityRoots.Core.Models.LandParcel", b =>
                {
                    b.Property<int>("ParcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParcelId"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParcelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParcelId");

                    b.HasIndex("FarmId");

                    b.ToTable("LandParcels");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Merchant", b =>
                {
                    b.Property<int>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MerchantId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusinessDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CityRoots.Core.Models.OpenInvestmentCycle", b =>
                {
                    b.Property<int>("OpenInvestmentCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpenInvestmentCycleId"));

                    b.Property<string>("AvailableProfitTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentInvestorCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentTotalInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedFinancialGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxInvestorsAllowed")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OpenInvestmentCycleId");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("OpenInvestmentCycles");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CycleId")
                        .HasColumnType("int");

                    b.Property<int?>("HarvestId")
                        .HasColumnType("int");

                    b.Property<string>("PayeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaypalOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Statue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CycleId");

                    b.HasIndex("HarvestId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PaypalOrderId")
                        .IsUnique()
                        .HasFilter("[PaypalOrderId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CityRoots.Core.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("PurchaseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseRequestId"));

                    b.Property<int>("HarvestId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RequestedAmount")
                        .HasColumnType("float");

                    b.Property<decimal>("RequestedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseRequestId");

                    b.HasIndex("HarvestId");

                    b.HasIndex("MerchantId");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Rate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FarmerId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Recommendations.InteractionOfInvestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("interactionOfInvestors");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Recommendations.InteractionOfMerchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HarvestId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("interactionOfMerchants");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CycleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("CityRoots.Core.Models.ScheduleNotificationLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("scheduleId")
                        .HasColumnType("int");

                    b.Property<int>("scheduleNotificationType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scheduleId");

                    b.ToTable("scheduleNotificationLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CityRoots.Core.Models.Chat", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "Receiver")
                        .WithMany("ReceivedChats")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "Sender")
                        .WithMany("SentChats")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Crop", b =>
                {
                    b.HasOne("CityRoots.Core.Models.CropType", "CropType")
                        .WithMany("crops")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Cycle", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Crop", "Crop")
                        .WithMany("Cycles")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.LandParcel", "LandParcel")
                        .WithMany("Cycles")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("CityRoots.Core.Models.CycleNotificationLog", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("CityRoots.Core.Models.CycleUpdate", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany("CycleUpdates")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farm", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farmer", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Farmer")
                        .HasForeignKey("CityRoots.Core.Models.Farmer", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CityRoots.Core.Models.FavoriteFarmers", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "FarmerUser")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FarmerUser");
                });

            modelBuilder.Entity("CityRoots.Core.Models.FeedBack", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "User")
                        .WithMany("FeedBacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Harvest", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Crop", "Crop")
                        .WithMany("Harvests")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId");

                    b.HasOne("CityRoots.Core.Models.Farmer", "Farmer")
                        .WithMany("Harvests")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Cycle");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("CityRoots.Core.Models.HarvestNotificationLog", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Harvest", "harvest")
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("harvest");
                });

            modelBuilder.Entity("CityRoots.Core.Models.InvestmentRequest", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany("InvestmentRequests")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.Investor", "Investor")
                        .WithMany("InvestmentRequests")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Investor", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Investor")
                        .HasForeignKey("CityRoots.Core.Models.Investor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CityRoots.Core.Models.LandParcel", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Farm", "Farm")
                        .WithMany("LandParcels")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Merchant", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Merchant")
                        .HasForeignKey("CityRoots.Core.Models.Merchant", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Notification", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CityRoots.Core.Models.OpenInvestmentCycle", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithOne("OpenInvestmentCycle")
                        .HasForeignKey("CityRoots.Core.Models.OpenInvestmentCycle", "CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Payment", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId");

                    b.HasOne("CityRoots.Core.Models.Harvest", "Harvest")
                        .WithMany()
                        .HasForeignKey("HarvestId");

                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.ApplicationUser", "Payer")
                        .WithMany("Payments")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Harvest");

                    b.Navigation("Payee");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("CityRoots.Core.Models.PurchaseRequest", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Harvest", "Harvest")
                        .WithMany("Purchases")
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.Merchant", "Merchant")
                        .WithMany("Purchases")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Harvest");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Schedule", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Cycle", "Cycle")
                        .WithMany("Schedules")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("CityRoots.Core.Models.ScheduleNotificationLog", b =>
                {
                    b.HasOne("CityRoots.Core.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("scheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityRoots.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CityRoots.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CityRoots.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Farmer")
                        .IsRequired();

                    b.Navigation("FeedBacks");

                    b.Navigation("Investor")
                        .IsRequired();

                    b.Navigation("Merchant")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("ReceivedChats");

                    b.Navigation("SentChats");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Crop", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Harvests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.CropType", b =>
                {
                    b.Navigation("crops");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Cycle", b =>
                {
                    b.Navigation("CycleUpdates");

                    b.Navigation("InvestmentRequests");

                    b.Navigation("OpenInvestmentCycle")
                        .IsRequired();

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farm", b =>
                {
                    b.Navigation("LandParcels");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Farmer", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Harvests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Harvest", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Investor", b =>
                {
                    b.Navigation("InvestmentRequests");
                });

            modelBuilder.Entity("CityRoots.Core.Models.LandParcel", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("CityRoots.Core.Models.Merchant", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
